language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'create database ketchup_test;' -U postgres
  - psql -d ketchup_test -f ./db/migrations/01_sex.sql -f ./db/migrations/02_users.sql -f ./db/migrations/03_post.sql
